name: Generate package-lock.json
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - name: Commit package-lock.json
        run: |
          git config --global user.email ${{secrets.MAIL}}
          git config --global user.name "chitose-jp"
          git add package-lock.json
          git commit -m "Generate package-lock.json"
          git push
